### ISSUE TITLE
Point should not be moved by command

### ISSUE THREAD

**Issue by sooheon** [d12frosted/flyspell-correct#14]
Whether a match does or does not occur (at point or before), point should be left in place after correction.  Make use of save-excursion?

**Comment by d12frosted** [comment]
Thanks for reporting.

**Comment by d12frosted** [comment]
I investigated this issue a bit. Looks like `flyspell-get-word` moves the point. But I wonder what is the desired behaviour. There are following possible solutions:

1. Move point to the end of word in any case.
2. Move point to the end of word only on successful correction.
3. Don't move point at all. 

End of word here means the end of word as flyspell understands it. 

Looks like all packages built around `flyspell-get-word` use behaviour (1). And everyone is happy about it. Because it's not common to try to correct the word without any mistakes :D 

I'll leave this issue open for now to see what others have to say :)

**Comment by sooheon** [comment]
Hm I guess if this function continues to be called for word at point, this behaviour is fine. However, if we allow to correct words away from point, like a sentence or two ago, the point should not move, imo. Then, it makes sense just to not have it move in any case, for consistency. FWIW, I'm coming from speck, and it has the behaviour I described: point never moves when correcting in either direction, or on unsuccessful invocation.

**Comment by d12frosted** [comment]
I know it took quite a while, but I think that current master has desired behavior. Cheers? 😸
