### ISSUE TITLE
Posframe Support?

### ISSUE THREAD

**Issue by arkhan** [d12frosted/flyspell-correct#49]
Regards

it is possible to add support for [posframe](https://github.com/tumashu/posframe) as an interface

thank you very much, great job

**Comment by d12frosted** [comment]
Hi @arkhan,

I've never used `postframe` and from the documentation, it seems that it's used only for showing information and it has no functionality to select an item from a list. In this sense, it won't be easy, though possible. Please correct me if I'm wrong.

**Comment by d12frosted** [comment]
Since `postframe` doesn't provide out-of-box functionality to select a value from the a list I am marking this issue as a won't fix (just for visibility). 

If someone really want to have `postframe` as an interface, then I suggest to extend `postframe` (either in the upstream repository or create a dedicated package) and then ping me or even better - create a PR to this repo 😸

**Comment by d12frosted** [comment]
Closing for the lack of activity,
