### ISSUE TITLE
Can't break out of rapid mode

### ISSUE THREAD

**Issue by WorldsEndless** [d12frosted/flyspell-correct#60]
Helm user here (don't know if that matters). 

I often need to stop a spell-correcting session in mid stride, for example if my spell error is "liket his" and I need to just go and to a `C-t` to fix it. However, it seems impossible to break out of rapid mode since `C-g` just skips a single step. If I'm spellchecking a large chunk of text with many errors, I need to `C-g` for every single mistype. There should definitely be some way to break out of rapid mode mid-process.

**Comment by d12frosted** [comment]
@WorldsEndless thank you for the report. Helm is really relevant as it seems that it eats the `C-g` and does not properly propagate it to the calling function. That's why `flyspell-correct-wrapper` doesn't know that it's time to stop. Doesn't happen with ivy. Will check other interfaces and will look for a fix.

**Comment by d12frosted** [comment]
Ok, I found a solution. Everything already works with helm, but now I need to test other interfaces 😸

**Comment by d12frosted** [comment]
@WorldsEndless hey, did you have a chance to test it? 😸 does it work now?

**Comment by WorldsEndless** [comment]
It works perfectly! Thanks!
